### ISSUE TITLE
ERROR: remote server responded with status 404 (NotFoundHttpException)

### ISSUE THREAD

**Issue by 8qBITs** [CamiloHernandez/fossil#1]
Error: ERROR: remote server responded with status 404 (NotFoundHttpException)

For some reason pterodactyl denies api access even tho i have enabled it

**Comment by ccuetoh** [comment]
Hi! Thanks for submitting an issue.

In order to see what's going on I would need to know a couple of things:
-  What version of Pterodactyl/WISP are you using?
-  Did the error occurred when authenticating or when executing a request? If so which request?
-  Could you please provide the code snippet that caused the error?

Do keep in mind that this library is not regularly maintained and might have compatibility issues with more recent versions of the Pterodactyl API.
